JSON_CONTENT = {"Content-type": "application/json"}

ENV_VAR_NEXUS_ENDPOINT = "NEXUS_ENDPOINT"
ENV_VAR_NEXUS_PREFIX = "NEXUS_PREFIX"
ENV_VAR_NEXUS_NAMESPACE = "NEXUS_NAMESPACE"
ENV_VAR_BLAZEGRAPH = "BLAZEGRAPH_ENDPOINT"
